### ISSUE TITLE
Change branch dist

### ISSUE THREAD

**Issue by hmanhng** [Gerg-L/spicetify-nix#172]
Some extensions have moved files to the `dist` branch
Specifically I see `powerBar` and `playlistIcons`

**Comment by Gerg-L** [comment]
Yeah I need to go through a verify that all the apps, exentions, and themes
- work
- haven't moved 
- have better forks

and see what other ones are out there that need packaged

**Comment by Gerg-L** [comment]
Should be fixed in #208
