### ISSUE TITLE
Cannot install custom apps - "Something went wrong"

### ISSUE THREAD

**Issue by GaviTSRA** [Gerg-L/spicetify-nix#217]
Hi! I cannot get it to correctly install spicetify. Every time i add custom apps like lyricsPlus, it goes to this:
![image](https://github.com/user-attachments/assets/d63d29dc-efef-4218-942d-c1f002f27841)
I have also tried enabling only the adblock extension, which doesn't break spotify but also doesn't block ads.

I am new to NixOS so this might just be a skill issue.
This is part of what i have:
```nix
programs.spicetify =
    let
     spicePkgs = spicetify-nix.legacyPackages.${pkgs.system};
    in
    {
      enable = true;
      enabledExtensions = with spicePkgs.extensions; [
        adblock
      ];
      enabledCustomApps = with spicePkgs.apps; [
          marketplace
          lyricsPlus
        ];
      theme = spicePkgs.themes.catppuccin;
    };
```

Please let me know if you need to see anything else of my configuration.

**Comment by Gerg-L** [comment]
what you're doing should work, can you share your whole config?

**Comment by Gerg-L** [comment]
closing as stale, feel free to reopen if you still have this issue
