### ISSUE TITLE
update the flake file

### ISSUE THREAD

**Issue by sachinchaudhary1808** [Gerg-L/spicetify-nix#219]
https://github.com/rxri/spicetify-extensions/issues/16

cuz of this issue can u update the flake file ?

**Comment by Gerg-L** [comment]
Wait a day for CI update

**Comment by sachinchaudhary1808** [comment]
> Wait a day for CI update

idk what is CI but okay

**Comment by Gerg-L** [comment]
https://en.m.wikipedia.org/wiki/Continuous_integration
