### ISSUE TITLE
Feature request: Pywal ~ Hot color switching

### ISSUE THREAD

**Issue by Arqamz** [Gerg-L/spicetify-nix#222]
Im not sure if this is just a nix issue. The wiki does mention this is supported
![image](https://github.com/user-attachments/assets/28b6b0ef-6b5c-496a-a3bf-6c70e4e77885)

On nixos to change color.ini in my theme doesnt change anything. Here is how I've installed spicetify
![image](https://github.com/user-attachments/assets/7b964bae-8de0-4a35-8f78-e721fb5e0b72)

**Comment by gigamonster256** [comment]
It seems like it is supported, you would need to define customColorScheme in your spicetify configuration and build it up as an attribute set mapping the thing you want to color (things like text/subtext in the example you gave) to the correct Xresources color (background, foreground, etc)

**Comment by Arqamz** [comment]
Could you tell me where exactly I need to define customColorScheme. I have this color.ini but Im not sure exactly where in my nixos configuration for building spicetify I need to add this.
```
[Base]
main_fg                               = ${xrdb:color3}
secondary_fg                          = ${xrdb:color6}
main_bg                               = ${xrdb:color0}
sidebar_and_player_bg                 = ${xrdb:color0}
cover_overlay_and_shadow              = 000000
indicator_fg_and_button_bg            = ${xrdb:color3}
pressing_fg                           =  FF5C86
slider_bg                             = ${xrdb:color1}
sidebar_indicator_and_hover_button_bg = ${xrdb:color2}
scrollbar_fg_and_selected_row_bg      = ${xrdb:color5}
pressing_button_fg                    = ${xrdb:color6}
pressing_button_bg                    = ${xrdb:color4}
selected_button                       = ${xrdb:color2}
miscellaneous_bg                      = ${xrdb:color1}
miscellaneous_hover_bg                = ${xrdb:color4}
preserve_1                            = FFFFFF
```

An example snippet would be extremely helpful thank you

**Comment by Gerg-L** [comment]
under `programs.spicetify`
 ```nix
colorScheme = "custom";
customColorScheme = {
 #translated ini values
};
```
Also
<https://github.com/NotAShelf/Basix>
<https://github.com/Misterio77/nix-colors>
<https://github.com/arcnmx/base16.nix>
One of these may help

**Comment by NotAShelf** [comment]
https://github.com/NotAShelf/Basix is clearly superior :trollface: 

(unironically)

**Comment by Arqamz** [comment]
@Gerg-L after hacking away for far too long I haven't been able to figure it out. Could you please look into the issue again and confirm if I really basix? @NotAShelf suggested that using toINI should work aswelll. But it doesnt look like it. Could you provide me with the exact snippet, I just want my pywal colors to work on spicetify.

![image](https://github.com/user-attachments/assets/0f03795c-2eea-4364-a468-f7dda0523459)
![image](https://github.com/user-attachments/assets/9b38a83d-58c5-4796-afde-2ce283681dea)
Both these and various other tweaks involving extra speech marks or less of them aren't working. 
```
error: A definition for option `programs.spicetify.customColorScheme.base' is not of type `string'. Definition values:
       - In `/etc/nixos/imports/user.nix':
           {
             cover_overlay_and_shadow = "000000";
             indicator_fg_and_button_bg = "xrdb:color3";
             main_bg = "xrdb:color0";
             main_fg = "xrdb:color3";
           ...
```

Would you be so kind as to provide me with an actual snippet based on what I've showed you.

**Comment by NotAShelf** [comment]
FYI I've never actually used a custom colorscheme with spicetify. My suggestion to use toINI was based on Gerg's comment:

> under `programs.spicetify`
> 
> ```nix
> colorScheme = "custom";
> customColorScheme = {
> #translated ini values
> };
> ```

Based on the error, I'd assume you do not need toINI - but just an attribute set of strings, e.g., 

```nix
customColorScheme = {
   foo = "bar";
   baz = "qux";
};

**Comment by Arqamz** [comment]
@Gerg-L 
![image](https://github.com/user-attachments/assets/556c1978-51a2-44b5-b482-1c4ec0394a83)

Trying to use xrdb is failing for me, I've added `xorg.xrdb` to both my environment packages and my user packages but it still doesnt seem to work

Here's my config
![image](https://github.com/user-attachments/assets/b0d5c8ff-c063-4a0f-833f-41149d8bbff1)

**Comment by Gerg-L** [comment]
does xrdb colors work with spicetify on non-nixos?

**Comment by Arqamz** [comment]
> does xrdb colors work with spicetify on non-nixos?

I would hope so, it's in the official spicetify documentation. 

![image](https://github.com/user-attachments/assets/29eac959-3c0a-43fe-a5e5-1ef62569ff3b)

**Comment by Gerg-L** [comment]
after messing around with this a bit, using xrdb values is not possible while building inside the nix sandbox because spicetify needs the xrdb values to be present at build time. which would make using them pointless.

so I recommend using one of the previously mentioned nix color frameworks and setting all your color values that way for consistent theming across applications
