### ISSUE TITLE
Update theme

### ISSUE THREAD

**Issue by zDyant** [Gerg-L/spicetify-nix#223]
Bloom fork is now [Lucid](https://github.com/sanoojes/Spicetify-Lucid)

**Comment by Gerg-L** [comment]
i don't have any themes titled "bloomFork" or anything similar
i'm gonna assume you want Lucid in addition to bloom itself packaged

**Comment by Gerg-L** [comment]
closed by: https://github.com/Gerg-L/spicetify-nix/commit/55540653e20855a8ccb9723c3d9513965d5fd445
