### ISSUE TITLE
Spicetify not being applied

### ISSUE THREAD

**Issue by mirzahilmi** [Gerg-L/spicetify-nix#226]
I tried using spicetify as an home manager & nixos module but neither make my spotify change. It was never been working on my machine since i moved from [the argus's spicetify](https://github.com/the-argus/spicetify-nix), i don't really know what i did wrong here. Im in NixOS 24.05 and using the stable nixpkgs 24.05. Heres are my flake & the spicetify module config

```nix
# flake.nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager/release-24.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    spicetify-nix.url = "github:Gerg-L/spicetify-nix";
    spicetify-nix.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = {
    self,
    nixpkgs,
    home-manager,
    ...
  } @ inputs: let
    inherit (self) outputs;
    lib = nixpkgs.lib // home-manager.lib;
  in {
    nixosConfigurations = {
      "test" = lib.nixosSystem {
        modules = [./hosts/test];
        specialArgs = {inherit inputs outputs;};
      };
    };

    homeConfigurations = {
      "mirza@test" = lib.homeManagerConfiguration {
        modules = [./home/mirza.nix];
        pkgs = nixpkgs.legacyPackages.x86_64-linux;
        extraSpecialArgs = {inherit inputs outputs;};
      };
    };
  };
}
```

```nix
# spicetify.nix
{
  pkgs,
  inputs,
  lib,
  ...
}: let
  spicetify-nix = inputs.spicetify-nix;
  spicetifyPkgs = spicetify-nix.legacyPackages.${pkgs.system};
in {
  imports = [spicetify-nix.nixosModules.default];
  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [
      "spotify"
    ];
  programs.spicetify = {
    enable = true;
    enabledCustomApps = with spicetifyPkgs.apps; [
      betterLibrary
      historyInSidebar
      localFiles
      lyricsPlus
      marketplace
      nameThatTune
    ];
    enabledExtensions = with spicetifyPkgs.extensions; [
      adblock
      beautifulLyrics
      hidePodcasts
      history
      shuffle
      volumePercentage
    ];
  };
}
```

**Comment by ne-lande** [comment]
I have had the same issue. If you have Spotify installed elsewhere as a package, remove it or collision will occur.

**Comment by Gerg-L** [comment]
Yeah ne-lande has a good point, ensure you don't have spotify installed elsewhere

**Comment by mirzahilmi** [comment]
> I have had the same issue. If you have Spotify installed elsewhere as a package, remove it or collision will occur.

I dont have spotify installed anywhere beside from the spicetify, tried deleting it from /nix/store and rebuild but still no luck

**Comment by Ysujy** [comment]
@mirzahilmi If you had Spotify installed before, try deleting the Spotify folder in the .config directory.

**Comment by mirzahilmi** [comment]
> @mirzahilmi If you had Spotify installed before, try deleting the Spotify folder in the .config directory.

Still nothing happend, i delete the .config/spotify also .cache/spotify, but still no luck

![image](https://github.com/user-attachments/assets/9d0d495a-fd83-4c8e-aecc-2110aa2273f7)

**Comment by mirzahilmi** [comment]
Good news, i fixed it by changing `spicetifyPackage` to use spicetify-cli from unstable channel. I tried changing `spicetify-nix.inputs.nixpkgs.follows` to nixpkgs-unstable in my flake inputs but it does nothing, so i try changing it directly with the module option and now it works :D
