### ISSUE TITLE
Adblock has stopped working

### ISSUE THREAD

**Issue by mmed-hajnasr** [Gerg-L/spicetify-nix#227]
after an update i started getting ads and the PlayNext extension stopped working. other shortcuts and theme still works.

**Comment by Tomasz-Badura** [comment]
Same issue, adblock and shuffle extension doesn't work at all, but themes and custom apps work fine.

**Comment by zDyant** [comment]
+1

**Comment by honnip** [comment]
I have installed adblock, betterGenres, fullAlbumDate, songStats, copyToClipboard, copyLyrics, and these are working fine

---
```shell
> nix-shell -p nix-info --run "nix-info -m"
fetching path input 'path:/nix/store/bd4fmzws6n5542khxbifbkr6nrygi232-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7-zen1, NixOS, 24.11 (Vicuna), 24.11.20240831.12228ff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/honnip/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/honnip/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/honnip/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/honnip/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/honnip/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/store/kzqdn6jmm16fjryqiqd02yxn4prqbfgf-gnome-settings-daemon-46.0/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/nklmprvqqk3afpn6cbxsdgfz4gfpw1pw-lix-2.91.0/share`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/bd4fmzws6n5542khxbifbkr6nrygi232-source`
 ```

I don't know if it helps, but

**Comment by Gerg-L** [comment]
Yeah some people have reported this issue and i have genuinely no clue what is causing it, and have not been able to reproduce it on my system.
I've wiped my Spotify config and cache and directly `nix run` their spicetify config and it's functioned on my system

**Comment by zDyant** [comment]
> I have installed adblock, betterGenres, fullAlbumDate, songStats, copyToClipboard, copyLyrics, and these are working fine

I'm testing your config rn, nothing but the theme works, for some reason

will look if nix is messing with something up later

**Comment by DADA30000** [comment]
same for me right now
I'm on unstable, imma try removing that inputs.follows.nixpkgs

**Comment by DADA30000** [comment]
oh wait, it got fixed by itself after restarting, I think it happened to me after I cleaned up my .cache

**Comment by DADA30000** [comment]
Yep, the problem occurs when cleaning spotify cache

**Comment by mmed-hajnasr** [comment]
so how can we fix this do we clean the cache then reinstall? or does that makes it worse.

**Comment by DADA30000** [comment]
> so how can we fix this do we clean the cache then reinstall? or does that makes it worse.

just restart the spotify after the first time, and it should be fine, at least it was like this for me

**Comment by sachinchaudhary1808** [comment]
same here, only theme plugin works adblock etc dosen't,

**Comment by Gerg-L** [comment]
I've had the adblock not work a few times, but restarting my spotify has always fixed it thus far.

i don't currently think this is a spicetify-nix issue but rather a spicetify-cli or rxri's adblock itself

**Comment by zDyant** [comment]
Maybe it's an error from migration from the old spicetify-nix?

**Comment by Gerg-L** [comment]
adblock is now broken for me...
I haven't rebuilt in 10 days. i'm very confused

**Comment by sachinchaudhary1808** [comment]
> adblock is now broken for me... I haven't rebuilt in 10 days. i'm very confused

uhu

**Comment by DADA30000** [comment]
> adblock is now broken for me... I haven't rebuilt in 10 days. i'm very confused

probably spotify doing some shenanigans on their side, spotify is an electron app after all

**Comment by Gerg-L** [comment]
and after updating it's working again

**Comment by sachinchaudhary1808** [comment]
nvm it accidently started working for me now

**Comment by Gerg-L** [comment]
Gonna close this for now
