### ISSUE TITLE
Best way to utilize Stylix + spicetify-nix

### ISSUE THREAD

**Issue by GideonWolfe** [Gerg-L/spicetify-nix#228]
My goal is to have a `spicetify` theme who's colors are taken from [Stylix](https://github.com/danth/stylix). That way when my system theme changes, the Spotify theme will dynamically change. Before I started using NixOS, I had something similar rigged up using `pywal`, where I would generate the `colors.ini` file with the correct colors when `pywal` was run.

I don't really need to do any heavy CSS modification outside of the colors, so I was planning on choosing one of the styles I like (ie `Sleek`) and then just swapping the color values. From my perspective, there are a few ways of doing this, but I want to make it work "the nix way", so when I regenerate my `home-manager` config, the necessary files are changed. And it should be able to be set up decleratively, so manually cloning and modifying the builtin themes seems like a bad way to go. 

From my perspective, it seems like the solution is either;

* Modifying the `colors.ini` of the theme to create a new colorscheme definition that is populated with the `stylix` colors. But that would be prone to the above issue, a new `colors.ini` would have to be created which could conflict with the old one, and is just messy
* Using the `additionalCss` option to override the CSS variables with stylix colors. This could be done in the `spicetify-nix` configuration itself, something like

```nix
programs.spicetify = {
    theme = {
        additionalCss = ''
            :root {
                --spice-main-elevated: ${baseXX};
            }
        '';
    };
};
```

where `${baseXX}` will be replaced with the hex code of the desired `stylix` color.

What is your opinion on this?

**Comment by Gerg-L** [comment]
Use the customColorScheme option:
<https://github.com/Gerg-L/nixos/blob/master/hosts%2Fgerg-desktop%2Fspicetify.nix#L22-L39>
Here's an example from my config
It's a direct toINI which replaces the colors.ini

**Comment by GideonWolfe** [comment]
Wow, replied within 5 minutes with the exact answer to my question. Thanks a million!

**Comment by GideonWolfe** [comment]
If anyone comes across this in the future, I added the following to my config to approximate a "good looking" color scheme using `stylix` variables

```nix
{ pkgs, config, spicetify-nix, ... }: 

with config.lib.stylix.colors;

{

    programs.spicetify =
    let spicePkgs = spicetify-nix.legacyPackages.${pkgs.system};
    in {
      ...
      theme = spicePkgs.themes.sleek;
      colorScheme = "custom";
      customColorScheme = {
        "text"               = "${magenta}";
        "subtext"            = "${base05}";
        "nav-active-text"    = "${bright-green}";
        "main"               = "${base00}";
        "sidebar"            = "${base00}";
        "player"             = "${base00}";
        "card"               = "${base00}";
        "shadow"             = "${base02}";
        "main-secondary"     = "${base01}";
        "button"             = "${orange}";
        "button-secondary"   = "${bright-cyan}";
        "button-active"      = "${orange}";
        "button-disabled"    = "${base0D}";
        "nav-active"         = "${magenta}";
        "play-button"        = "${green}";
        "tab-active"         = "${yellow}";
        "notification"       = "${blue}";
        "notification-error" = "${red}";
        "playback-bar"       = "${bright-green}";
        "misc"               = "${bright-magenta}";
      };
    };
}
```
