### ISSUE TITLE
Feature request: sandboxing

### ISSUE THREAD

**Issue by Nishimara** [Gerg-L/spicetify-nix#235]
I'm not sure if it's me being schyzo or sandboxing for spotify sounds reasonable. I'm suggesting implementing something like

```nix
options.programs.spicetify.sandoxing.enable = mkEnableOption "Enable sandbox for spotify";
```

which will isolate spotify with bubblewrap. There is two good solutions to that: write shell script that will call bubblewrap and do the magic, like steam  [does](https://github.com/NixOS/nixpkgs/blob/5c33791df3046a15de4969fb110129cfa2fe492c/pkgs/by-name/st/steam/package.nix) in nixpkgs, or use [nixpak](https://github.com/nixpak/nixpak), but it'll add extra input to flake.

**Comment by Gerg-L** [comment]
bubblewrap is linux only so it'd break darwin support, you can implement it yourself using `dontInstall = true;` and the `spicedSpotify` config option which ends is the spiced spotify package

**Comment by nukdokplex** [comment]
> it'd break darwin support

i think you can make it linux-only feature by adding assert and some logic

**Comment by Nishimara** [comment]
Yes, it may go around `stdenv.hostPlatform.isLinux` and if it's false then throw an error

**Comment by Gerg-L** [comment]
I know it's possible but it can't be bothered to implement it myself, i also need to rework the implementation of spotify-tray which is also only available on linux. maybe after i rework that i'll get around to it
