### ISSUE TITLE
Cant finish build

### ISSUE THREAD

**Issue by havvvsen** [Gerg-L/spicetify-nix#238]
Everything was working fine when I was using this in the nixosConfigurations but I just want it to be managed by home-manager
am getting this error

spicetify v2.36.14
Backing up app files:
OK
Extracting:
OK
Preprocessing:
warning Cannot fetch version tag for CSS mappings
err: Get "https://api.github.com/repos/spicetify/cli/releases/latest": dial tcp: lookup api.github.com >
info Fetching remote CSS map for newer compatible tag version: 2.36.14
info Cannot fetch remote CSS map. Using local CSS map instead...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:

**Comment by Gerg-L** [comment]
share your config

**Comment by Cauterium** [comment]
I've got the exact same issue with the following config:

```nix
{
  pkgs,
  lib,
  config,
  inputs,
  ...
}: let
  spicetifyPkgs = inputs.spicetify-nix.legacyPackages.${pkgs.system};
in {
  imports = [inputs.spicetify-nix.homeManagerModules.default];

  options = {
    spicetify.enable = lib.mkEnableOption "Enables Spicetify";
  };

  config = lib.mkIf config.spicetify.enable {
    programs.spicetify = {
      enable = true;
      theme = spicetifyPkgs.themes.comfy;

      colorScheme = "custom";
      customColorScheme = with config.colorScheme.palette; {
        text = "${base07}";
        subtext = "${base05}";
        nav-active-text = "${base0C}";
        main = "${base01}";
        main-secondary = "${base00}";
        main-elevated = "${base01}";
        main-transition = "${base01}";
        highlight = "${base03}";
        highlight-elevated = "${base03}";
        sidebar = "${base00}";
        player = "${base00}";
        card = "${base00}";
        window = "${base00}";
        shadow = "${base00}";
        button = "${base0C}";
        button-secondary = "${base07}";
        button-active = "${base0C}";
        button-disabled = "${base07}";
        nav-active = "${base02}";
        tab-active = "${base02}";
        notification = "${base03}";
        notification-error = "${base08}";
        playback-bar = "${base0C}";
        play-button = "${base0C}";
        play-button-active = "${base0C}";
        progress-fg = "${base0C}";
        progress-bg = "${base01}";
        pagelink-active = "${base03}";
        radio-btn-active = "${base03}";
        misc = "000000";
      };

      enabledExtensions = with spicetifyPkgs.extensions; [
        fullAppDisplay
      ];
    };
  };
}
```

I've already tried using different themes, using the Nixos module instead of the home manager module and commenting out enabledExtensions, but I still get the same error, no matter what I do.

**Comment by Gerg-L** [comment]
It looks like Spotify got version bumped in nixpkgs while spicetify-cli didn't, it's probably that. I can investigate more tonight

**Comment by Gerg-L** [comment]
It's because you're on stable, either pin a specific working spicetify-nix rev or set `spicetifyPackage` to `spicetify-cli` from unstable, or update to unstable (24.11 comes out soon anyways).

**Comment by GuessWhatBBQ** [comment]
Gerg-L is correct and their solution works as well. Here's what worked for me and the changes I had to make to my flakes.

```nix
  programs.spicetify =
    let
      spicePkgs = inputs.spicetify-nix.legacyPackages.${pkgs.system};
    in
    {
      enable = true;
      spicetifyPackage = inputs.nixpkgs-unstable.legacyPackages."${pkgs.system}".spicetify-cli; # added this
    };
```
Made the following changes to my `flake.nix`

```nix
    ......
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05";

    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable"; # added this
    ......
```

> [!NOTE]  
> Switching to unstable would definitely be smarter

[Source](https://discourse.nixos.org/t/using-an-unstable-package-inside-of-a-flake/30641) used to understand how to get this to work for anyone else learning nix
