### ISSUE TITLE
Need help in first install

### ISSUE THREAD

**Issue by penzboti** [Gerg-L/spicetify-nix#240]
I'm only a few weeks into nix, and I just set up home-manager.

I have not yet been able to apply spicetify to spotify using spicetify-nix.
Is it supposed to apply automatically after ```home-manager build```?
Or after a full config build?
Or do I have to use the spicetify-cli?

In the latter case, spicetify-cli does not find the spotify location. Its asking me to set it myself, and I dont want to hard set it to the spotify in nixpkgs, because that would break very often. 

I will post my config if its needed for the issue-hunt.

Thank you in advance!

**Comment by Gerg-L** [comment]
You don't need to install Spicetify-cli or Spotify yourself.

The spicetify-nix module runs spicetify-cli on and then installs Spotify for you

**Comment by penzboti** [comment]
Thank you, now I got it working.
I pasted some code that I did not understand, which I figured out to be an outside toggle of some sorts. I removed it and now it works.
