### ISSUE TITLE
Loading extensions locally

### ISSUE THREAD

**Issue by 3333juul** [Gerg-L/spicetify-nix#241]
Is it possible to load extensions locally so i could edit their source code? I want to change bindings in "keyboardShortcut" extension. What is the best way to do it?

**Comment by Gerg-L** [comment]
yeah just set the `src` of the extension to a relative path instead of using a fetcher
for example
```nix
programs.spicetify.enabledExtensions = [
  ({
      src = ./relative/path;
      name = "keyboardShortcut.js";
  })
];
```

you will have to rebuild spotify every time something changes though so if you were developing a extension i would do something different

**Comment by 3333juul** [comment]
thanks
